/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#12131a",
        "surface-dim": "#12131a",
        "surface-bright": "#383940",
        "surface-container-lowest": "#0c0e14",
        "surface-container-low": "#1a1b22",
        "surface-container": "#1e1f26",
        "surface-container-high": "#282a31",
        "surface-container-highest": "#33343c",
        "on-surface": "#e2e1eb",
        "on-surface-variant": "#dfc0b2",
        "inverse-surface": "#e2e1eb",
        "inverse-on-surface": "#2f3037",
        outline: "#a78b7e",
        "outline-variant": "#584237",
        "surface-tint": "#ffb692",
        primary: "#ffb692",
        "on-primary": "#552000",
        "primary-container": "#f27121",
        "on-primary-container": "#541f00",
        "inverse-primary": "#9f4200",
        secondary: "#c8c6c9",
        "on-secondary": "#303033",
        "secondary-container": "#47464a",
        "on-secondary-container": "#b6b4b8",
        tertiary: "#c8c6c9",
        "on-tertiary": "#303033",
        "tertiary-container": "#98969a",
        "on-tertiary-container": "#2f2f32",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffdbcb",
        "primary-fixed-dim": "#ffb692",
        "on-primary-fixed": "#341100",
        "on-primary-fixed-variant": "#793100",
        "secondary-fixed": "#e4e2e5",
        "secondary-fixed-dim": "#c8c6c9",
        "on-secondary-fixed": "#1b1b1e",
        "on-secondary-fixed-variant": "#47464a",
        "tertiary-fixed": "#e4e1e5",
        "tertiary-fixed-dim": "#c8c6c9",
        "on-tertiary-fixed": "#1b1b1e",
        "on-tertiary-fixed-variant": "#47464a",
        background: "#12131a",
        "on-background": "#e2e1eb",
        "surface-variant": "#33343c",
        "surface-charcoal": "#121214",
        "surface-card": "#1C1C1F",
        "accent-orange-rich": "#F27121",
        "accent-orange-muted": "rgba(242, 113, 33, 0.1)",
        "match-score-fill": "#F27121",
        "status-success": "#22C55E",
        "status-error": "#EF4444",
        "text-primary": "#F4F4F5",
        "text-secondary": "#A1A1AA",
      },
      fontFamily: {
        heading: ["Space Grotesk", "ui-sans-serif", "system-ui"],
        body: ["Inter", "ui-sans-serif", "system-ui"],
      },
      fontSize: {
        h1: ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        h2: ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        h3: ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", fontWeight: "700", letterSpacing: "0.05em" }],
        "match-score": ["14px", { lineHeight: "1", fontWeight: "700" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "32px",
        xl: "48px",
        gutter: "20px",
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
}
